<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Alunos_model extends CI_Model
{
	function __construct()
	{
		parent::__construct();
	}
/****************************************************************/
/*
 * Get dados_boleto by id
 */
/****************************************************************/
	function getAluno($id)
	{
		return $this->db->get_where('alunos',array('id'=>$id))->row_array();
	}
/****************************************************************/
/*
 * Get Alunos by snqc
 */
/****************************************************************/
	function getSnqc($id)
	{
		$this->db->select('a.id, a.cpf, a.nome, a.endereco, a.cidade, a.cep, a.snqc, a.email, b.sigla');
		$this->db->from('alunos AS a');
		$this->db->join('estados AS b', 'b.id = a.estado_id');
		$this->db->where(array('snqc'=>$id));
		return $this->db->get()->row_array();
	}
/****************************************************************/
/*
 * Get all dados_boletos count
 */
/****************************************************************/
	function getAllAlunosCount()
	{
		$this->db->from('alunos');
		return $this->db->count_all_results();
	}
/****************************************************************/
/*
 * Get all dados_boletos
 */
/****************************************************************/
	function getAllAlunos($params = array())
	{
		$this->db->order_by('id', 'desc');
		if(isset($params) && !empty($params))
		{
			$this->db->limit($params['limit'], $params['offset']);
		}
		return $this->db->get('alunos')->result_array();
	}
/****************************************************************/
/*
 * function to add new dados_boleto
 */
/****************************************************************/
	function add_dados_boleto($params)
	{
		$this->db->insert('alunos',$params);
		return $this->db->insert_id();
	}
/****************************************************************/
/*
 * function to update dados_boleto
 */
/****************************************************************/
	function update_dados_boleto($id,$params)
	{
		$this->db->where('id',$id);
		return $this->db->update('alunos',$params);
	}
/****************************************************************/
/*
 * function to delete dados_boleto
 */
/****************************************************************/
	function deleteAlunos($id)
	{
		return $this->db->delete('alunos',array('id'=>$id));
	}
/****************************************************************/
}
