<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Mensagem_model extends CI_Model
{
	function __construct()
	{
		parent::__construct();
	}
/****************************************************************/
/*
 * Get dados_boleto by id
 */
/****************************************************************/
	function getMensagem($id)
	{
		return $this->db->get_where('mensagem',array('mensagem_id'=>$id))->row_array();
	}
/****************************************************************/
/*
 * Get all Mensagem
 */
/****************************************************************/
	function getAll()
	{
		$this->db->order_by('mensagem_id', 'asc');
		return $this->db->get('mensagem')->result_array();
	}
/****************************************************************/
}
