<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Alunos_model extends CI_Model
{
	function __construct()
	{
		parent::__construct();
	}
/****************************************************************/
/*
 * Get Alunos by id
 */
/****************************************************************/
	function getAluno($id)
	{
		return $this->db->get_where('alunos',array('id'=>$id))->row_array();
	}
/****************************************************************/
	function listarAlunos()
	{
		$this->db->order_by('aluno_nome', 'asc');
		return $this->db->get('aluno')->result_array();
	}
/****************************************************************/
	function listarEmpresas()
	{
		$this->db->order_by('empresa_nome', 'asc');
		return $this->db->get('empresa')->result_array();
	}
/****************************************************************/
}
