<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
/*************************************************/
class Alunos_controller extends CI_Controller{
	function __construct()
	{
		parent::__construct();
		if (!$this->ion_auth->logged_in()){
			redirect('index.php/auth', 'refresh');
		}
	}
/*************************************************/
/*
 * Listing of dados_boletos
 */
/*************************************************/
	function index()
	{
		$params['limit'] = RECORDS_PER_PAGE;
		$params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

		$config = $this->config->item('pagination');
		$config['base_url'] = site_url('alunos/index?');
		$config['total_rows'] = $this->alunos->getAllAlunosCount();
		$this->pagination->initialize($config);

		$data['alunos'] = $this->alunos->getAllAlunos($params);

		foreach ($data['alunos'] as $key => $row) {
			$cpf_cnpj = new Validacpfcnpj($row['cpf']);
			$data['alunos'][$key]['v_cpf_cnpj'] = $cpf_cnpj->valida();
		}

		$data['_view'] = 'alunos/index';
		$this->load->view('layouts/main',$data);
	}
/*************************************************/
/*
 * Editing a dados_boleto
 */
/*************************************************/
	function edit($id)
	{
		// check if the dados_boleto exists before trying to edit it
		$data['dados_boleto'] = $this->Dados_boleto_model->get_dados_boleto($id);

		if(isset($data['dados_boleto']['id']))
		{
			if(isset($_POST) && count($_POST) > 0)
			{
				$params = array(
					'nosso_numero' => $this->input->post('nosso_numero'),
					'numero_documento' => $this->input->post('numero_documento'),
					'data_vencimento' => $this->input->post('data_vencimento'),
					'data_documento' => $this->input->post('data_documento'),
					'data_processamento' => $this->input->post('data_processamento'),
					'valor_boleto' => $this->input->post('valor_boleto'),
					'endereco1' => $this->input->post('endereco1'),
					'endereco2' => $this->input->post('endereco2'),
					'demonstrativo1' => $this->input->post('demonstrativo1'),
					'demonstrativo2' => $this->input->post('demonstrativo2'),
					'valor_unitario' => $this->input->post('valor_unitario'),
					'cpf_cnpj' => $this->input->post('cpf_cnpj'),
					'nome' => $this->input->post('nome'),
					'email' => $this->input->post('email'),
					'situacao' => $this->input->post('situacao'),
				);

				$this->Dados_boleto_model->update_dados_boleto($id,$params);
				redirect('dados_boleto/index');
			}
			else
			{
				$data['_view'] = 'dados_boleto/edit';
				$this->load->view('layouts/main',$data);
			}
		}
		else
			show_error('The dados_boleto you are trying to edit does not exist.');
	}
/*************************************************/
	function getBoleto($id)
	{

		ob_end_clean();
		ob_start();

		$this->boleto->bradesco($this->Dados_boleto_model->getBoleto($id));
	}
/*************************************************/
	public function addBoleto($id)
	{
		$data['alunos'] = $this->alunos->getAluno($id);
		$data['_view'] = 'alunos/addBoleto';
		$this->load->view('layouts/main',$data);
	}
/*************************************************/
}
